### Numpy.array中的运算

In [1]:
n = 10
L = [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
L*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
%%time
n = 100000
L = [i for i in range(n)]
A = []
for i in L:
    A.append(2*i)

Wall time: 90.1 ms


直接用生成表达式比用for循环可快一倍左右

In [4]:
%%time
A = [2*i for i in L]

Wall time: 20 ms


In [5]:
import numpy as np
L = np.arange(n)
L

array([    0,     1,     2, ..., 99997, 99998, 99999])

同样的生成表达式用numpy中的array会快非常多

In [6]:
%%time
A = np.array(2*i for i in L)

Wall time: 2 ms


并且np中的array支持乘法运算

In [7]:
A

array(<generator object <genexpr> at 0x000001C65B2A2F10>, dtype=object)

In [8]:
%%time
A = 2*L

Wall time: 0 ns


In [9]:
A

array([     0,      2,      4, ..., 199994, 199996, 199998])

### Universal Function

In [11]:
X = np.arange(1,16).reshape(3,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [13]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [14]:
X / 2 # 浮点除

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [15]:
X // 2 # 整除

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [16]:
X ** 2 #乘方

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [17]:
X % 2 #取余

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [18]:
1 / X #取倒数

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [19]:
np.abs(X) #绝对值

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
np.sin(X) #取正弦， cos, tan,...也都有

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [21]:
np.exp(X) # e的x次方

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [22]:
np.power(3,X) # 3的x次方 = 3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [23]:
np.log(X) # 以e为底

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [24]:
np.log2(X) # 以2为底

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

### 矩阵与矩阵间的运算

In [25]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [28]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [29]:
A + B

array([[10, 11],
       [12, 13]])

In [30]:
A * B # A 与 B 对应元素相乘

array([[ 0, 10],
       [20, 30]])

numpy中的操作都是对应元素的操作<br>
如果想做矩阵间的乘法，需用 A.dot（B）

In [31]:
A.dot(B) # 矩阵的乘法 第（i，j）位元素即 表A i 行 乘以 表B j列 的和

array([[10, 10],
       [50, 50]])

In [32]:
A

array([[0, 1],
       [2, 3]])

In [33]:
A.T # 矩阵的转置

array([[0, 2],
       [1, 3]])

### 向量与矩阵的运算

In [35]:
v = np.array([1,2])
v

array([1, 2])

In [36]:
A

array([[0, 1],
       [2, 3]])

In [37]:
v + A

array([[1, 3],
       [3, 5]])

In [39]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [40]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [41]:
np.tile(v,(2,1)) #行向量堆叠两次， 列向量堆叠一次

array([[1, 2],
       [1, 2]])

In [42]:
v

array([1, 2])

In [43]:
A

array([[0, 1],
       [2, 3]])

In [45]:
v * A

array([[0, 2],
       [2, 6]])

In [46]:
v.dot(A)

array([4, 7])

In [47]:
A.dot(v) #会自动把v当作列向量

array([2, 8])

### 矩阵的逆

矩阵必须是方阵，才会存在逆矩阵

In [48]:
A

array([[0, 1],
       [2, 3]])

In [50]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [51]:
A.dot(invA) #原矩阵乘以逆矩阵得到单位矩阵，对角线都为1

array([[1., 0.],
       [0., 1.]])

In [52]:
invA.dot(A) #与上相同

array([[1., 0.],
       [0., 1.]])

对于非方阵矩阵，可求其伪逆矩阵。原矩阵乘伪逆矩阵会得到单位矩阵（对角线都是1）

In [53]:
X = np.arange(10).reshape(2,5)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
pinvX = np.linalg.pinv(X) #伪逆矩阵
pinvX

array([[-3.20000000e-01,  1.20000000e-01],
       [-1.80000000e-01,  8.00000000e-02],
       [-4.00000000e-02,  4.00000000e-02],
       [ 1.00000000e-01, -1.38777878e-17],
       [ 2.40000000e-01, -4.00000000e-02]])

In [59]:
X.dot(pinvX)

array([[ 1.00000000e+00, -1.66533454e-16],
       [ 1.33226763e-15,  1.00000000e+00]])