## Numpy.array basic operation

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [5]:
x.ndim #查看数组维度数

1

In [6]:
X.ndim

2

In [7]:
x.shape #查看shape

(10,)

In [8]:
X.shape #三行五列

(3, 5)

In [9]:
x.size #查看元素个数

10

In [10]:
X.size

15

### numpy.array的数据访问

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 单个数据访问

In [12]:
x[3] #通过索引访问

3

In [13]:
x[-1] #倒数

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
X[2][3]

13

In [18]:
X[(2,3)] #比起[][]，更推荐这种访问方式

13

In [19]:
X[1,2] #可省略圆括号

7

#### 切片

In [20]:
x[0:5] # 从0到5，不包括5

array([0, 1, 2, 3, 4])

In [21]:
x[:5]

array([0, 1, 2, 3, 4])

In [22]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
x[::2] #第三个参数是步长

array([0, 2, 4, 6, 8])

In [24]:
x[::-2] #步长可为负数，表倒数

array([9, 7, 5, 3, 1])

In [25]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
X[:2, :3] #前两行，前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [27]:
X[:2][:3] #注，这个会解析成前两行的前三行 ***-> 所以推荐使用逗号

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
X[:2,::2] #前两行，列步长为2

array([[0, 2, 4],
       [5, 7, 9]])

In [29]:
X[::-1,::-1] #反转

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [30]:
X[0]

array([0, 1, 2, 3, 4])

In [31]:
X[0,:] #只取一行

array([0, 1, 2, 3, 4])

In [32]:
X[:,0] #只取一列

array([ 0,  5, 10])

#### 子矩阵的访问

子矩阵与原矩阵会互相影响

In [34]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [37]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [38]:
X # subX的改变也会改变原X
#因为在numpy中用的是引用（python的array不会改变）

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [39]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
subX #X的改变也会影响subX

array([[0, 1, 2],
       [5, 6, 7]])

不互相影响的方法 -> 使用copy

In [41]:
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [43]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [44]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape -> 不变数据 变数据维度

In [45]:
x.shape

(10,)

In [46]:
x.ndim #查看维度

1

In [47]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
x.ndim #reshape不会改变x自身

1

In [50]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
B.ndim

2

In [54]:
B.shape

(1, 10)

In [56]:
x.shape

(10,)

In [57]:
x.reshape(5,-1) #不指定列，只指定有5行

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [58]:
x.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
x.reshape(3,-1) #但不能这样，3无法被10整除

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

### 合并操作

In [60]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [61]:
x

array([1, 2, 3])

In [62]:
y

array([3, 2, 1])

In [63]:
np.concatenate([x,y]) #concat

array([1, 2, 3, 3, 2, 1])

In [64]:
z = np.array(['zz','zz'])

In [65]:
np.concatenate([x,y,z])

array(['1', '2', '3', '3', '2', '1', 'zz', 'zz'], dtype='<U11')

In [67]:
A = np.array([[1,2,3],
              [4,5,6]])

In [69]:
np.concatenate([A,A]) #和行拼

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
np.concatenate([A,A],axis=1) #和列拼

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [77]:
np.concatenate([A,[x]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [80]:
A2 = np.concatenate([A, x.reshape(1,-1)])
A2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [81]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
np.vstack([A,x]) #vertical stack, 即使维度不同也可垂直叠加
#容错性更好

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [83]:
B = np.full((2,2),666)
B

array([[666, 666],
       [666, 666]])

In [84]:
np.hstack([A,B]) #水平堆叠

array([[  1,   2,   3, 666, 666],
       [  4,   5,   6, 666, 666]])

In [85]:
np.concatenate([A,B],axis = -1)

array([[  1,   2,   3, 666, 666],
       [  4,   5,   6, 666, 666]])

### 分割操作

In [86]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.split(x, [3,7]) #分割点，3 7

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [88]:
np.split(x, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [89]:
np.split(x,[5]) #注意与上行的区别
#带了方括号表示分割点，没带表示分割成几段

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [90]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
np.split(A, [2]) #默认基于行分割

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [92]:
np.split(A,[2],axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [93]:
np.vsplit(A,[2]) #vertical split垂直

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [94]:
np.hsplit(A,[2]) #hieratical split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [95]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
X, y = np.hsplit(data, [-1])

In [97]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [98]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [99]:
y[:,0] #将y变成向量

array([ 3,  7, 11, 15])