## Numpy.array 简介

np.array, np.zeros, np.ones, np.full, x.dtype<br>
******************************************
np.arange, np.linspace<br>
******************************************
np.random.randint, np.random.random, np.random.normal, np.random.seed

In [1]:
import numpy

In [2]:
numpy.__version__

'1.14.0'

In [3]:
import numpy as np

### Python List特点

灵活无类型限制，反之缺点是效率较慢

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[3]

3

In [8]:
L[3] = 100
L

[0, 1, 2, 100, 4, 5, 6, 7, 8, 9]

In [9]:
L[3] = 'Zzz'
L

[0, 1, 2, 'Zzz', 4, 5, 6, 7, 8, 9]

### Array

限定类型，运算更快。但未配备向量，矩阵运算。

In [10]:
import array

'i' 表示int型

In [12]:
arr = array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[3]

3

In [14]:
arr[3] = 100
arr

array('i', [0, 1, 2, 100, 4, 5, 6, 7, 8, 9])

In [15]:
arr[3] = 'zzz'

TypeError: an integer is required (got type str)

上面错误表示array这种数组是限定类型的，只能存同类型。虽然降低了灵活性，但提高了效率。
但array只将存在其中的数据当（二维）数组来看，未将数据看作向量或矩阵，也未配备相应的运算。

### Numpy.array

限定类型，有矩阵向量运算

In [17]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
nparr[3]

3

In [19]:
nparr[3] = 100
nparr

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [20]:
nparr[3] = 'zzz'

ValueError: invalid literal for int() with base 10: 'zzz'

In [23]:
nparr.dtype #查类型，结果-> 32位整型

dtype('int32')

In [26]:
nparr[3] = 3.14 #浮点型会自动转化成整型 
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
nparr2 = np.array([1,2,3.0])
nparr2.dtype

dtype('float64')

### other method to new a numpy.array

不指定类型时，默认都是浮点型。

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.zeros((3,5)) # 3*5 3行五列

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.full((3,5),'666')

array([['666', '666', '666', '666', '666'],
       ['666', '666', '666', '666', '666'],
       ['666', '666', '666', '666', '666']], dtype='<U3')

In [38]:
np.full((3,5),'66.0')

array([['66.0', '66.0', '66.0', '66.0', '66.0'],
       ['66.0', '66.0', '66.0', '66.0', '66.0'],
       ['66.0', '66.0', '66.0', '66.0', '66.0']], dtype='<U4')

In [37]:
np.full(shape=(3,5),fill_value='Zz')

array([['Zz', 'Zz', 'Zz', 'Zz', 'Zz'],
       ['Zz', 'Zz', 'Zz', 'Zz', 'Zz'],
       ['Zz', 'Zz', 'Zz', 'Zz', 'Zz']], dtype='<U2')

### arange

python中range方法的步长不可为浮点数<br>
np.arrange的步长可以是浮点数<br>
步长默认都为1

In [39]:
[i for i in range(0, 20, 2)] # 起始点，终点（不包含），步长

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [41]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [43]:
np.arange(10) #省略起始点，默认为0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [45]:
np.linspace(0,20,5) #起始点，终点，等长截取点的个数（包括0和20）

array([ 0.,  5., 10., 15., 20.])

### random

In [48]:
np.random.randint(0,10) #[0,10)，随机数 取不到10

0

In [47]:
np.random.randint(0,10,10) #第三个参数->数组/向量

array([9, 9, 4, 9, 2, 7, 2, 2, 2, 3])

In [49]:
np.random.randint(4,5,size=10)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [50]:
np.random.randint(4,8,size=(3,5))

array([[5, 5, 7, 7, 4],
       [5, 5, 7, 5, 5],
       [4, 4, 4, 6, 4]])

#### 生成相同随机数， seed种子

In [53]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [54]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

#### 0到1间的随机浮点数

0 到 1 间均匀分布的随机数

In [55]:
np.random.random() 

0.2811684913927954

In [57]:
np.random.random(3) #个数

array([0.31644109, 0.15551206, 0.73460987])

正态分布随机数

In [58]:
np.random.normal() #默认均值0，方差1

0.6706843844614704

In [59]:
np.random.normal(10, 100) #均值10，方差100

53.40469388604746

In [60]:
np.random.normal(0,1,(3,5)) #第三个参数 大小，三行五列的矩阵

array([[ 0.78337092, -0.47082667,  0.61360982, -0.21747638,  0.22196962],
       [-1.86735182, -0.25584759, -1.76438083, -0.94249688, -1.58045861],
       [ 0.90472662, -0.82628327,  0.82101369,  0.36712592,  1.65399586]])

#### 在notebook中查询参数或模块，在后面加问号

In [61]:
np.random.normal? #弹出窗显示

In [62]:
help(np.random.normal)#或在本页面显示

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap