### 测试集与训练集

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [29]:
X = iris.data
y = iris.target

In [5]:
X.shape # 150行 -> 150个样本， 四列属性

(150, 4)

In [6]:
y.shape # 150个标记，每个样本一个标记

(150,)

### 分离测试数据集与训练数据集

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

不能简单的取前100为训练数据集，因为对于此数据集y是排好序的。

乱序方法1：<br>
把x，y先合并成一个矩阵，乱序处理后再分离。

In [17]:
z = np.hstack([X,y.reshape(-1,1)])
z[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

In [18]:
np.random.shuffle(z)
z[:5]

array([[5.6, 2.9, 3.6, 1.3, 1. ],
       [5.9, 3. , 5.1, 1.8, 2. ],
       [6.5, 3. , 5.5, 1.8, 2. ],
       [5.3, 3.7, 1.5, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ]])

In [24]:
X = z[:,:-2]
y = z[:,-1]

In [25]:
X[:5]

array([[5.6, 2.9, 3.6],
       [5.9, 3. , 5.1],
       [6.5, 3. , 5.5],
       [5.3, 3.7, 1.5],
       [4.9, 3.1, 1.5]])

In [27]:
y[:5]

array([1., 2., 2., 0., 0.])

乱序方法2：

In [30]:
shuffle_indexes = np.random.permutation(len(X))
shuffle_indexes

array([ 50,  63, 143,  76, 142,  94, 130,   8,  32,  40,  21,  12, 129,
        86, 119, 108, 126,  69, 111,  55,  13,  88,  42, 113,   0,  47,
        68,  30,   9,  35,  91,  93,  43,  39, 144,  95, 131,  62, 149,
        87,   2,  72,  66,  17, 136, 117, 114,  14, 134,  74,   4, 112,
        98, 141, 147,  92,  52,  34, 132, 127,  41,  49,  38, 107,  44,
       106,  27,  20,  48,  33,   6, 121,  29,   5,  15,  10, 110,  65,
        81,  90,  73,   3,  71, 133, 109,  64, 120, 100,  46,  19,  79,
       135, 101,  25,  60, 128, 116, 125,  70,  23,  58,  61,  26, 124,
       148, 103,  89, 104,  78,  85,  57, 139, 102,  77,  80,  97, 146,
        24,  36, 122, 145,  83,  59,  53, 138, 137,  99, 123, 140, 118,
         7,  56, 105,  84,  37,  54,  28,  45,  96,  82,  51, 115,  31,
        67,  11,  75,  16,  22,   1,  18])

In [37]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio) # 有可能是浮点数,所以要转换
test_size

30

In [38]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [39]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [40]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)
